
spring.application.name = raizcampesina

# CONEXION MYSQL
spring.datasource.url = jdbc:mysql://localhost:3306/raiz_campesina?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username = root
spring.datasource.password = Qwertyuiop!0

# DRIVER
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto = none
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true

# THYMELEAF
spring.thymeleaf.cache = false

# PUERTO
server.port = 8081

#IPs LOCALES DISPONIBLES
server.address=0.0.0.0

